# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
#   node: circleci/node@4.1
# jobs: 
#   build:
#     docker:
#       - image: cimg/node:15.1
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  #
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#           cache-key: 'yarn.lock'
#   test:
#     parallelism: 1
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#           cache-key: 'yarn.lock'
#       - run: 
#           name: Wait on LH
#           command: dockerize -wait tcp://localhost:5432 -timeout 1m
# workflows:
#   buildAndTest:
#     jobs:
#       - build
#       - test:
#         - run: 
#           name: npm tests
#           command: npm run test:e2e
#           requires: 
#             - build

version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'
      - cypress/run:
          requires:
            - cypress/install
          record: false
          start: 'npm run test'
